In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a = (1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [3]:
type(a)

tuple

In [5]:
b = np.array(a)
print(b)

[1 2 3 4 5]


In [6]:
type(b)

numpy.ndarray

In [7]:
b.ndim # in order to find the dimsn

1

In [8]:
b.shape # no.of rows and no.columns

(5,)

In [9]:
b.size # total number of elements present in an array

5

In [10]:
b.dtype ## data type of my array

dtype('int32')

#### Speed Comaprison numpy vs core python

In [11]:
import time as tm

In [12]:
size_1 = 10000000
def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 5.7382402420043945
numpy = 0.0884852409362793


In [13]:
my_list =[2,3,4,6,7,8]

In [15]:
type(my_list)

list

In [14]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 6, 7, 8])

In [16]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [17]:
array_3.ndim

2

In [18]:
array_3.shape

(3, 3)

In [19]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [22]:
a = np.array([1, 2, 3,7,5,1], ndmin = 10) 
print (a)
np.ndim(a)

[[[[[[[[[[1 2 3 7 5 1]]]]]]]]]]


10

In [23]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [24]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [26]:
array_3[0] 

array([1, 2, 3])

In [27]:
array_3[2,1]

8

In [28]:
array_3[2,0]

7

In [29]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [30]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_3[:,0] # Acessing Column

array([1, 4, 7])

In [32]:
array_3[2:,:]

array([[7, 8, 9]])

In [33]:
array_3[0:2 , 0:1]

array([[1],
       [4]])

### Array Initilization

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [36]:
np.arange(1.8,10.4,3)

array([1.8, 4.8, 7.8])

In [37]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [38]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [39]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [43]:
np.linspace(1,10,10) # (start,end,no of values)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
np.linspace(1,10,20) # (start,end,no of values)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [45]:
np.linspace(1.23,4.7,10)

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [46]:
np.eye(4,4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.random.rand(2)

array([0.75623081, 0.42806832])

In [49]:
np.random.rand(10)

array([0.72979573, 0.52075435, 0.07986269, 0.88184858, 0.07390884,
       0.22739537, 0.08639644, 0.73074228, 0.98155747, 0.13928671])

In [50]:
np.random.rand(2,2)

array([[0.51462445, 0.00858303],
       [0.90734203, 0.96979769]])

In [59]:
np.random.rand()

0.7364241606094935

In [60]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
arr1 =np.random.rand(9).reshape(3,3)

In [63]:
arr1

array([[0.03228174, 0.84660387, 0.63525303],
       [0.31683972, 0.29620677, 0.52489993],
       [0.2124228 , 0.24282486, 0.1791904 ]])

In [64]:
arr1.ndim

2

In [65]:
array_3.max()

9

In [67]:
array_3.min()

1

In [68]:
array_3.mean()

5.0

In [69]:
array_3.min(axis=0) ## minimum value column wise

array([1, 2, 3])

In [70]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
array_3.max(axis=0) ## minimum value column wise

array([7, 8, 9])

In [73]:
array_3.max(axis=1) ## minimum value column wise

array([3, 6, 9])

In [74]:
array_3.min(axis=1) ## minimum value column wise

array([1, 4, 7])

In [75]:
array_3.mean(axis=1)

array([2., 5., 8.])

In [76]:
array_3.flatten() #2D to 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
array_3.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)
print(B)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [80]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
print("Adding to arrays: ")
print(A + B)

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [82]:
print("Substracting Two Arrays")
print(A-B)

Substracting Two Arrays
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [83]:
print("\nMultiplying two arrays: ")
print(A * B)


Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [84]:
print("Multiplying one Array with scalar")
print(3*A)

Multiplying one Array with scalar
[[12 30 33]
 [63 66 69]
 [93 96 99]]


In [85]:
print("Matrix Multiplication")
print(np.dot(A,B))

Matrix Multiplication
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [86]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [87]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [89]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [90]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [91]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print (np.around(a)) 

[[12. 24.]
 [33. 46.]]


In [92]:
print (np.around(a, decimals = 1))

[[11.7 23.7]
 [33.2 45.9]]


In [93]:
print (np.around(a, decimals = 2))

[[11.67 23.66]
 [33.21 45.89]]


In [94]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [95]:
A.sum() ## SUM OF ALL THE DATA 

187

In [96]:
A.sum(axis=0) ## row wise

array([56, 64, 67])

In [97]:
A.sum(axis=1) ## row wise

array([25, 66, 96])

In [98]:
np.std(A)

9.88576729757121

In [99]:
np.median(A)

22.0

### Subsetting array

In [100]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [101]:
subset1 = A[: , 0] = 1  ## sub set element before postion 0 to value 1

In [102]:
subset1

1

In [103]:
A

array([[ 1, 10, 11],
       [ 1, 22, 23],
       [ 1, 32, 33]])

In [105]:
var = [1,2,3]

In [106]:
var[0] = 22

In [107]:
var 

[22, 2, 3]

In [108]:
np.concatenate([A,B],axis=1)

array([[ 1., 10., 11.,  1.,  1.,  1.],
       [ 1., 22., 23.,  1.,  1.,  1.],
       [ 1., 32., 33.,  1.,  1.,  1.]])

In [109]:
np.random.randint(2,50,(3,4))

array([[46,  7, 44, 42],
       [17,  5,  5, 20],
       [16, 47, 35, 30]])

In [113]:
np.random.randint(0,2,(2,2))

array([[0, 1],
       [1, 0]])

In [116]:
np.random.randint(2,50, (2, 3, 4) )

array([[[42, 10, 15,  7],
        [ 6, 13, 25, 23],
        [26, 25,  4, 27]],

       [[34, 34, 29, 37],
        [43, 44, 27, 26],
        [16, 48, 27, 27]]])

In [117]:
np.random.rand(3,4)

array([[0.1621649 , 0.79929146, 0.91422096, 0.03574186],
       [0.8630111 , 0.88455519, 0.11361643, 0.06814784],
       [0.44229321, 0.89325658, 0.29172931, 0.70396567]])

In [118]:
a = np.random.randn(4,4)

In [119]:
a

array([[ 0.6551302 ,  0.45288333, -0.28001209,  0.51247987],
       [-0.20046642,  0.66937999, -2.35876928, -0.66418172],
       [-0.76914074, -0.5196551 , -0.10551841,  0.94784523],
       [ 0.12154048,  0.66477743,  0.83039625, -0.0682871 ]])